version: "3.9"
services:
  server:
    build: .
    restart: always
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=classpath:/configurations
    networks:
      - my_spring-cloud-network

networks:
  my_spring-cloud-network:
    driver: bridge