version: "3.9"
services:
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
  config:
    image: jfcaraballo/spring-cloud-config-server
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=classpath:/configurations
