version: "3.9"
services:
  jms:
    image: apache/activemq-artemis:latest
    ports:
      - "8161:8161"
      - "61616:61616"
  zipkin:
    image: openzipkin/zipkin:latest
    ports:
      - "9411:9411"
  config:
    image: jfcaraballo/spring-cloud-config-server
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=native
      - SPRING_CLOUD_CONFIG_SERVER_NATIVE_SEARCH_LOCATIONS=classpath:/configurations
