server:
  port: 8888

spring:
  application:
    name: spring-cloud-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/configurations
  security:
    user:
      name: mySuperUserName
      password: mySuperPassword

## Logging
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.cloud: DEBUG
    org.springframework.web.servlet: DEBUG
    org.springframework.web.servlet.mvc: DEBUG




## Spring Cloud Config Server with Git
##spring.cloud.config.server.git.uri=https://github.com/jesusfc/spring-cloud-config-server.git
##spring.cloud.config.server.git.clone-on-start=true
##spring.cloud.config.server.git.search-paths={application}




